apiVersion: v1
data:
  deployment.yaml: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: {{ include "hello-world.fullname" . }}
      labels:
        {{- include "hello-world.labels" . | nindent 4 }}
    spec:
      replicas: {{ .Values.replicaCount }}
      selector:
        matchLabels:
          {{- include "hello-world.selectorLabels" . | nindent 6 }}
      template:
        metadata:
          labels:
            {{- include "hello-world.selectorLabels" . | nindent 8 }}
        spec:
          serviceAccountName: {{ include "hello-world.serviceAccountName" . }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              ports:
                - name: http
                  containerPort: 80
                  protocol: TCP
              livenessProbe:
                httpGet:
                  path: /
                  port: http
              readinessProbe:
                httpGet:
                  path: /
                  port: http
  service.yaml: |
    apiVersion: v1
    kind: Service
    metadata:
      name: {{ include "hello-world.fullname" . }}
      labels:
        {{- include "hello-world.labels" . | nindent 4 }}
    spec:
      type: {{ .Values.service.type }}
      ports:
        - port: {{ .Values.service.port }}
          targetPort: http
          protocol: TCP
          name: http
      selector:
        {{- include "hello-world.selectorLabels" . | nindent 4 }}
  serviceaccount.yaml: |
    {{- if .Values.serviceAccount.create -}}
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: {{ include "hello-world.serviceAccountName" . }}
      labels:
        {{- include "hello-world.labels" . | nindent 4 }}
      {{- with .Values.serviceAccount.annotations }}
      annotations:
        {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- end }}
kind: ConfigMap
metadata:
  name: test-cm5
